# Generated by Django 5.1.6 on 2025-02-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
