name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'

    - name: Install Dependencies
      run: npm install

    - name: Run Database Migrations
      run: npm run migrate
    
    - env:
        DATABASE_URL: psql://todo_user:todo_pass@localhost:5432/todo_db
      
    - name: Build code
      run: npm run build
